on:
  workflow_dispatch:
    inputs:
      trigger:
        required: false
        default: 'workflow_dispatcher'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=0.0.8 --no-build --output .
    - name: Upload nuget symbol package to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: Ragent.Des/Ragent.Des/Ragent.Des.0.0.8.nupkg
        tag: v0.0.7
